// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC01() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1872, 996));
    driver.findElement(By.name("search")).click();
    vars.put("search", js.executeScript("return \"Nồi cơm điện\""));
    driver.findElement(By.name("search")).sendKeys(vars.get("search").toString());
    driver.findElement(By.cssSelector(".vns-SEARCH")).click();
    vars.put("item1", driver.findElement(By.cssSelector("div:nth-child(1) > .product-card-two__Card-sc-1lvbgq2-0 .product-card-two__Title-sc-1lvbgq2-6")).getText());
    vars.put("item2", driver.findElement(By.cssSelector("div:nth-child(2) > .product-card-two__Card-sc-1lvbgq2-0 .product-card-two__Title-sc-1lvbgq2-6")).getText());
    System.out.println(vars.get("item1").toString());
    System.out.println(vars.get("item2").toString());
    vars.put("check1", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("item1"),vars.get("search")));
    vars.put("check2", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("item2"),vars.get("search")));
    assertEquals(vars.get("check1").toString(), "true");
    assertEquals(vars.get("check2").toString(), "true");
    driver.close();
  }
}
