// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC02Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC02() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1872, 996));
    {
      WebElement element = driver.findElement(By.cssSelector(".react-multi-carousel-item--active a > span > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,3845)");
    js.executeScript("window.scrollTo(0,7782)");
    js.executeScript("window.scrollTo(0,9677)");
    js.executeScript("window.scrollTo(0,10791)");
    js.executeScript("window.scrollTo(0,11648)");
    js.executeScript("window.scrollTo(0,12400)");
    js.executeScript("window.scrollTo(0,13113)");
    vars.put("count", driver.findElements(By.xpath("//*[@id=\"trung-dau-hu--c33\"]/div[2]/div/div")).size());
    System.out.println(vars.get("count").toString());
    vars.put("x", js.executeScript("return 1"));
    while ((Boolean) js.executeScript("return (arguments[0]<=arguments[1])", vars.get("x"),vars.get("count"))) {
      driver.findElement(By.cssSelector("#trung-dau-hu--c33 .product-card__Card-sc-1q72qgw-0:nth-child(vars.get("x").toString()) > .box__Box-sc-1h894p0-0 span")).click();
      vars.put("x", js.executeScript("return arguments[0]+1", vars.get("x")));
    }
    js.executeScript("window.scrollTo(0,13142)");
    vars.put("item", driver.findElement(By.cssSelector(".cart-menu__Box-sc-1uxxzqy-1 > p")).getText());
    vars.put("item", js.executeScript("return parseInt(arguments[0].match(/\\((\\d+)\\)/)[1])", vars.get("item")));
    System.out.println(vars.get("item").toString());
    assertEquals(vars.get("count").toString(), "vars.get("item").toString()");
    driver.close();
  }
}
