// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC03Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC03() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1872, 996));
    vars.put("item", driver.findElement(By.cssSelector(".cart-menu__Box-sc-1uxxzqy-1 > p")).getText());
    vars.put("item", js.executeScript("return parseInt(arguments[0].match(/\\((\\d+)\\)/)[1])", vars.get("item")));
    System.out.println(vars.get("item").toString());
    vars.put("x", js.executeScript("return 1"));
    vars.put("sum", js.executeScript("return 0"));
    if ((Boolean) js.executeScript("return (arguments[0] == 0)", vars.get("item"))) {
      System.out.println("\"Giò hàng chưa có sản phẩm nên chưa tính và so sánh được\"");
    } else {
      while ((Boolean) js.executeScript("return (arguments[0] <= arguments[1])", vars.get("x"),vars.get("item"))) {
        js.executeScript("window.scrollTo(0,335)");
        driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0:nth-child(1)")).click();
        vars.put("itemx", driver.findElement(By.cssSelector(".cart-itemstyle__ItemBox-sc-yuve81-0:nth-child(vars.get("x").toString()) .cart-itemstyle__Total-sc-yuve81-8")).getText());
        vars.put("itemx", js.executeScript("return parseFloat(arguments[0].match(/\\d+(\\.\\d+)?/)[0] +parseFloat(\'00\'))", vars.get("itemx")));
        vars.put("itemx", js.executeScript("return parseFloat(arguments[0].toFixed(3) +arguments[1])", vars.get("itemx"),vars.get("sum")));
        vars.put("sum", js.executeScript("return parseFloat(arguments[0]) + parseFloat(arguments[1])", vars.get("itemx"),vars.get("sum")));
        vars.put("sum", js.executeScript("return arguments[0].toFixed(3)", vars.get("sum")));
        System.out.println(vars.get("sum").toString());
        vars.put("x", js.executeScript("return arguments[0]+1", vars.get("x")));
        vars.put("itemx", js.executeScript("return arguments[0]+1", vars.get("itemx")));
      }
      driver.findElement(By.cssSelector(".cart-menu__Box-sc-1uxxzqy-1 > p")).click();
      vars.put("gia", driver.findElement(By.cssSelector(".indexstyle__Row-sc-1jxz1oi-1:nth-child(1) > span:nth-child(2)")).getText());
      driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0:nth-child(1)")).click();
      vars.put("gia", js.executeScript("return arguments[0]", vars.get("gia")));
      vars.put("gia", js.executeScript("return (parseFloat(arguments[0].match(/\\d+(\\.\\d+)?/)[0]) + parseFloat(\'00\')).toFixed(3)", vars.get("gia")));
      System.out.println(vars.get("gia").toString());
      vars.put("gia", driver.findElement(By.cssSelector(".indexstyle__Row-sc-1jxz1oi-1:nth-child(1) > span:nth-child(2)")).getText());
      vars.put("check", js.executeScript("return typeof(arguments[0]) === typeof(arguments[1])", vars.get("gia"),vars.get("sum")));
      assertEquals(vars.get("check").toString(), "true");
    }
    driver.close();
  }
}
