// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC05Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC05() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("Bắp cải");
    driver.findElement(By.cssSelector(".vns-SEARCH")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .product-card-two__Card-sc-1lvbgq2-0 .product-card-two__FrameImage-sc-1lvbgq2-2")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .box__Box-sc-1h894p0-0")).click();
    vars.put("x1", driver.findElement(By.cssSelector(".active > .box__Box-sc-1h894p0-0")).getText());
    driver.findElement(By.cssSelector(".ml5")).click();
    driver.findElement(By.cssSelector(".popoverCartstyle__PopoverCartWrapper-sc-1kjh00v-0 .button__StyledButton-sc-6gren8-0")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".cart-itemstyle__Weight-sc-yuve81-7")).click();
    vars.put("x2", driver.findElement(By.cssSelector(".cart-itemstyle__Weight-sc-yuve81-7")).getText());
    System.out.println(vars.get("x1").toString());
    System.out.println(vars.get("x2").toString());
    vars.put("check", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("x2"),vars.get("x1")));
    assertEquals(vars.get("check").toString(), "true");
    driver.close();
  }
}
