// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC06LocSPTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC06LocSP() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,1558)");
    js.executeScript("window.scrollTo(0,2499)");
    js.executeScript("window.scrollTo(0,3454)");
    js.executeScript("window.scrollTo(0,3788)");
    js.executeScript("window.scrollTo(0,4822)");
    driver.findElement(By.cssSelector("#hoa-pham-tay-rua--c10 .title")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0:nth-child(2) img")).click();
    vars.put("soLuongSP", driver.findElements(By.xpath("//*[@id=\"__next\"]/div[1]/div/div[2]/div/div/div[2]/div[3]/div[2]/div/div")).size());
    vars.put("brand", driver.findElement(By.cssSelector(".brand-filter")).getText());
    vars.put("x", js.executeScript("return 1"));
    vars.put("count", js.executeScript("return 0"));
    while ((Boolean) js.executeScript("return (arguments[0]<=arguments[1])", vars.get("x"),vars.get("soLuongSP"))) {
      vars.put("tenSP", driver.findElement(By.xpath("//*[@id=\"__next\"]/div[1]/div/div[2]/div/div/div[2]/div[3]/div[2]/div/div[vars.get("x").toString()]/div/a/div")).getText());
      vars.put("check", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("tenSP"),vars.get("brand")));
      if ((Boolean) js.executeScript("return (arguments[0])", vars.get("check"))) {
        vars.put("count", js.executeScript("return  arguments[0]+1", vars.get("count")));
      }
      vars.put("x", js.executeScript("return arguments[0]+1", vars.get("x")));
    }
    System.out.println(vars.get("count").toString());
    assertEquals(vars.get("count").toString(), "soLuongSP");
    driver.close();
  }
}
