// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC07DangKyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC07DangKy() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.cssSelector(".MuiButton-outlined > .text-capitalize")).click();
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("123");
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    driver.findElement(By.id("userName-helper-text")).click();
    assertThat(driver.findElement(By.id("userName-helper-text")).getText(), is("Số điện thoại gồm 10 số. Ví dụ: 0908000000"));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    driver.findElement(By.id("password-helper-text")).click();
    assertThat(driver.findElement(By.id("password-helper-text")).getText(), is("Mật khẩu phải có ít nhất 4 ký tự"));
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("0384331808");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    driver.findElement(By.id("fullName")).click();
    driver.findElement(By.id("fullName")).sendKeys("Hoàng Yên");
    driver.findElement(By.name("dobDate")).click();
    driver.findElement(By.name("dobDate")).sendKeys("21/06/2002");
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormControlLabel-root:nth-child(2) .PrivateSwitchBase-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiFormControlLabel-root:nth-child(2) .PrivateSwitchBase-input")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("div:nth-child(1) > .otpText")).sendKeys("5");
    driver.findElement(By.cssSelector("div:nth-child(2) > .otpText")).sendKeys("6");
    driver.findElement(By.cssSelector("div:nth-child(3) > .otpText")).sendKeys("6");
    driver.findElement(By.cssSelector("div:nth-child(4) > .otpText")).sendKeys("4");
    driver.findElement(By.cssSelector("div:nth-child(5) > .otpText")).sendKeys("7");
    driver.findElement(By.cssSelector("div:nth-child(5) > .otpText")).sendKeys("6");
    driver.findElement(By.cssSelector("div:nth-child(4) > .otpText")).sendKeys("4");
    driver.findElement(By.cssSelector("div:nth-child(5) > .otpText")).sendKeys("7");
    driver.findElement(By.cssSelector("div:nth-child(6) > .otpText")).sendKeys("5");
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".gzkZJu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(6) > .otpText")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .otpText")).sendKeys("5");
    driver.findElement(By.cssSelector("div:nth-child(2) > .otpText")).sendKeys("6");
    driver.findElement(By.cssSelector("div:nth-child(3) > .otpText")).sendKeys("6");
    driver.findElement(By.cssSelector("div:nth-child(4) > .otpText")).sendKeys("4");
    driver.findElement(By.cssSelector("div:nth-child(5) > .otpText")).sendKeys("7");
    driver.findElement(By.cssSelector("div:nth-child(6) > .otpText")).sendKeys("5");
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".gdNqjH"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".register-success__SubTitle-sc-1owmj9d-2")).click();
    driver.findElement(By.cssSelector(".register-success__Container-sc-1owmj9d-0 > div:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".register-success__SubTitle-sc-1owmj9d-2")).getText(), is("Bạn đã trở thành hội viên của WIN!"));
    driver.findElement(By.cssSelector(".register-success__Container-sc-1owmj9d-0")).click();
  }
}
