// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC08DangNhapTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC08DangNhap() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("123");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".v-btn__content-btn")).click();
    driver.findElement(By.cssSelector(".MuiAlert-message")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root")).click();
    assertThat(driver.findElement(By.cssSelector(".MuiAlert-message")).getText(), is("Tài khoản 8423 không tồn tại trong hệ thống."));
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("0384331808");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".v-btn__content-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).getText(), is("Hoàng Yên"));
  }
}
