// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC09QuenMatKhauTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC09QuenMatKhau() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.linkText("Quên mật khẩu?")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("0384331808");
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345");
    driver.findElement(By.id("password-helper-text")).click();
    assertThat(driver.findElement(By.id("password-helper-text")).getText(), is("Mật khẩu phải có ít nhất 6 ký tự"));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.id("confirmPassword")).click();
    driver.findElement(By.id("confirmPassword")).sendKeys("123");
    driver.findElement(By.id("confirmPassword-helper-text")).click();
    assertThat(driver.findElement(By.id("confirmPassword-helper-text")).getText(), is("Cả hai mật khẩu phải giống nhau"));
    driver.findElement(By.id("confirmPassword")).click();
    driver.findElement(By.id("confirmPassword")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".bg-login > .form-login")).click();
    driver.findElement(By.id("code")).click();
    driver.findElement(By.id("code")).sendKeys("123456");
    driver.findElement(By.cssSelector(".MuiPaper-root")).click();
    assertThat(driver.findElement(By.cssSelector(".MuiAlert-message")).getText(), is("Mã OTP không đúng, vui lòng nhập lại."));
    driver.findElement(By.cssSelector(".wrap-form-login")).click();
    driver.findElement(By.id("code")).sendKeys("687814");
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("0384331808");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".v-btn__content-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).getText(), is("Hoàng Yên"));
  }
}
