// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC10Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC10() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1552, 832));
    vars.put("user_name", driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).getText());
    System.out.println(vars.get("user_name").toString());
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(10)")).click();
    vars.put("strange_user", driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).getText());
    System.out.println(vars.get("strange_user").toString());
    vars.put("check_logout", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("user_name"),vars.get("strange_user")));
    assertEquals(vars.get("check_logout").toString(), "false");
    driver.close();
  }
}
