// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC11() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1552, 832));
    vars.put("address1", driver.findElement(By.cssSelector(".delivery-menu__Box2-sc-ltegci-2 > .bottom")).getText());
    driver.findElement(By.cssSelector(".delivery-menu__Box2-sc-ltegci-2 > .bottom")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".btnText")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".provincestyle__RowItem-sc-1n1p904-1:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".provincestyle__RowItem-sc-1n1p904-1:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".provincestyle__RowItem-sc-1n1p904-1:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".currentstyle__AddressInfo-sc-myfzhh-3 > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".currentstyle__AddressInfo-sc-myfzhh-3 > div:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".currentstyle__AddressInfo-sc-myfzhh-3 > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".currentstyle__AddressInfo-sc-myfzhh-3 > div:nth-child(1)")).click();
    vars.put("address_change", driver.findElement(By.cssSelector(".currentstyle__AddressInfo-sc-myfzhh-3 > div:nth-child(1)")).getText());
    driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0 > span")).click();
    driver.findElement(By.id("layout-header")).click();
    vars.put("address2", driver.findElement(By.cssSelector(".delivery-menu__Box2-sc-ltegci-2 > .bottom")).getText());
    System.out.println(vars.get("address2").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".popover-handler1 > .navigation-bar-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("check1", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("address_change"),vars.get("address2")));
    vars.put("check2", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("address1"),vars.get("address2")));
    assertEquals(vars.get("check1").toString(), "true");
    assertEquals(vars.get("check2").toString(), "false");
    driver.close();
  }
}
