// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC13Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC13() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".popover-accountstyle__PopoverWrapper-sc-itl4f8-0 > .popover-handler1 path:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".form-row:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".form-row:nth-child(1) > .input-wrapper")).click();
    driver.findElement(By.id("fullName")).sendKeys("Minh Khang");
    vars.put("name", driver.findElement(By.id("fullName")).getAttribute("value"));
    driver.findElement(By.cssSelector(".hLrTMn")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root")).click();
    assertThat(driver.findElement(By.cssSelector(".MuiAlert-message")).getText(), is("Cập nhật thành công!"));
    js.executeScript("window.scrollTo(0,413)");
    vars.put("name1", driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).getText());
    System.out.println(vars.get("name1").toString());
    System.out.println(vars.get("name").toString());
    vars.put("check", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("name1"),vars.get("name")));
    assertEquals(vars.get("check").toString(), "true");
  }
}
