// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC14Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC14() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector("#layout-header > div:nth-child(1)")).click();
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("tương ớt");
    driver.findElement(By.cssSelector(".vns-SEARCH")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .product-card-two__Card-sc-1lvbgq2-0 .product-card-two__FrameImage-sc-1lvbgq2-2")).click();
    driver.findElement(By.cssSelector(".product-detailsstyle__ProductTitle-sc-127s7qc-8")).click();
    vars.put("var", driver.findElement(By.cssSelector(".product-detailsstyle__ProductTitle-sc-127s7qc-8")).getText());
    vars.put("var1", js.executeScript("return arguments[0].substring(0,8)", vars.get("var")));
    System.out.println(vars.get("var1").toString());
    vars.put("x", js.executeScript("return 6"));
    while ((Boolean) js.executeScript("return (arguments[0]<=10)", vars.get("x"))) {
      vars.put("var2", driver.findElement(By.xpath("//*[@id=\"__next\"]/div[1]/div/div[2]/div/div/div/div[3]/div[2]/div/ul/li[vars.get("x").toString()]/div/div/a/h6")).getText());
      vars.put("check", js.executeScript("return arguments[0].includes(arguments[1])", vars.get("var2"),vars.get("var1")));
      vars.put("x", js.executeScript("return arguments[0]+1", vars.get("x")));
      System.out.println(vars.get("check").toString());
    }
    driver.close();
  }
}
