// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC15Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC15() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(8) > .item")).click();
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Minh Thiện");
    driver.findElement(By.id("phoneNo")).click();
    driver.findElement(By.id("phoneNo")).sendKeys("0365485543");
    driver.findElement(By.id("provinceCode")).click();
    driver.findElement(By.id("provinceCode-option-1")).click();
    driver.findElement(By.id("districtCode")).click();
    driver.findElement(By.id("districtCode-option-21")).click();
    driver.findElement(By.id("wardCode")).click();
    driver.findElement(By.id("wardCode-option-8")).click();
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("Đường 35");
    driver.findElement(By.id("isDefault")).click();
    driver.findElement(By.cssSelector(".gdNqjH")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root")).click();
    assertThat(driver.findElement(By.cssSelector(".MuiAlert-message")).getText(), is("Khách hàng không tồn tại trong hệ thống"));
    driver.close();
  }
}
