// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC17Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC17() {
    driver.get("https://winmart.vn/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,1558)");
    js.executeScript("window.scrollTo(0,2380)");
    js.executeScript("window.scrollTo(0,3180)");
    js.executeScript("window.scrollTo(0,3966)");
    js.executeScript("window.scrollTo(0,4524)");
    driver.findElement(By.cssSelector("#hoa-pham-tay-rua--c10 .title")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".category__StyledCollapse-sc-lz8fd5-10:nth-child(6) .box__Box-sc-1h894p0-0")).click();
    driver.findElement(By.cssSelector(".topRightFilter__SortSection-sc-2n9cnc-0 > .category__StyledCollapse-sc-lz8fd5-10:nth-child(1) .box__Box-sc-1h894p0-0")).click();
    vars.put("text", js.executeScript("return document.getElementsByClassName(\'product-card-two__Discount-sc-1lvbgq2-4\').length"));
    vars.put("values", js.executeScript("let values = []; for (let i = 0; i < document.getElementsByClassName(\'product-card-two__Discount-sc-1lvbgq2-4\').length; i++) { values.push(parseInt(document.getElementsByClassName(\'product-card-two__Discount-sc-1lvbgq2-4\')[i].textContent.replace(/[^0-9]/g, \"\"))); } return values;"));
    System.out.println(vars.get("text").toString());
    System.out.println(vars.get("values").toString());
    vars.put("isSorted", js.executeScript("values =arguments[0] ; isSorted = true; for (let i = 0; i < values.length - 1; i++) { if (values[i] < values[i + 1]) { isSorted = false; break; } } return isSorted;", vars.get("values")));
    if ((Boolean) js.executeScript("return (arguments[0])", vars.get("isSorted"))) {
      System.out.println("Danh sách được sắp xếp theo khuyến mãi tốt nhất");
    } else {
      System.out.println("Danh sách không được sắp xếp theo khuyến mãi tốt nhất");
    }
  }
}
