// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC20sanphamdamuaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC20sanphamdamua() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(7) > .item")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .customerstyle__StyledTableRow-sc-ds3fyt-7 > .width-column3")).click();
    driver.findElement(By.cssSelector(".customerstyle__StyledTableRow-sc-ds3fyt-7 > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".customerstyle__StyledTableRow-sc-ds3fyt-7 > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".customerstyle__StyledTableRow-sc-ds3fyt-7 > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".customerstyle__StyledTableRow-sc-ds3fyt-7")).click();
    vars.put("name1", driver.findElement(By.cssSelector(".customerstyle__StyledTableRow-sc-ds3fyt-7 > div:nth-child(1)")).getText());
    driver.findElement(By.cssSelector(".auth-menu__Box-sc-1ifavmo-0 > p")).click();
    driver.findElement(By.cssSelector(".auth-pop__StyleContainer-sc-rat0bw-0 > .customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(9) > .item")).click();
    driver.findElement(By.cssSelector(".product-card__Card-sc-1q72qgw-0")).click();
    vars.put("name2", driver.findElement(By.cssSelector(".product-card__Title-sc-1q72qgw-6")).getText());
    System.out.println(vars.get("name1").toString());
    System.out.println(vars.get("name2").toString());
    vars.put("check", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("name1"),vars.get("name2")));
    assertEquals(vars.get("check").toString(), "true");
    driver.close();
  }
}
