// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC23Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC23() {
    driver.get("https://winmart.vn//");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".cart-menu__Box-sc-1uxxzqy-1 > p")).click();
    driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0 span:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".delivery-slot-selectorstyle__DeliverySlotTimeWrapper-sc-1lgkqxu-6:nth-child(2) > .delivery-slot-selectorstyle__DeliverySlotTime-sc-1lgkqxu-8")).click();
    driver.findElement(By.cssSelector(".MuiFormControlLabel-root:nth-child(2) div > div")).click();
    driver.findElement(By.cssSelector(".common-field__FormControlLabel-sc-4t35v3-3:nth-child(1)")).click();
    driver.findElement(By.id("note")).click();
    driver.findElement(By.id("note")).click();
    driver.findElement(By.id("note")).sendKeys("em làm bt testcase");
    assertThat(driver.findElement(By.id("note")).getText(), is("em làm bt testcase"));
    vars.put("x", driver.findElement(By.id("note")).getAttribute("value"));
    driver.findElement(By.cssSelector(".order-successstyle__StyledPanelText-sc-wj9jwu-6:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(9) > .item")).click();
    driver.findElement(By.cssSelector(".customerstyle__SidebarMenu-sc-ds3fyt-4:nth-child(7) > .item")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) .width-column3")).click();
    driver.findElement(By.cssSelector(".payment-methods-section span:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".payment-methods-section span:nth-child(1)")).getText(), is("Ghi chú: Em đang làm bài tập testcase"));
    vars.put("note", driver.findElement(By.cssSelector(".payment-methods-section span:nth-child(1)")).getText());
    vars.put("check", js.executeScript("return arguments[0].toUpperCase().includes(arguments[1].toUpperCase())", vars.get("note"),vars.get("x")));
    assertEquals(vars.get("check").toString(), "true");
    driver.findElement(By.cssSelector(".button__StyledButton-sc-6gren8-0 > div > div")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".order-successstyle__StyledLeftContent-sc-wj9jwu-2")).click();
  }
}
